name:                elab
version:             0.1.0.0
github:              "Trebor-Huang/elab"
license:             MIT
author:              "Trebor"
maintainer:          "treborhuang@foxmail.com"
copyright:           "2021 Trebor Huang"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A simple elaborator for dependent type.

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.0
- containers >= 0.6

library:
  source-dirs: src

executables:
  elab-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elab

tests:
  elab-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elab
